package:
  name: libclock_gettime_wrapper
  version: 2.17

source:
  - path: ./

build:
  number: 3
  string: {{ PKG_BUILDNUM }}
  ignore_run_exports:
    - libgcc-ng
  
requirements:
  build:
    - {{ compiler('c') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
  run:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}

about:
  home: open-ce
  license: LGPL
  license_family: LGPL
  license_file: LICENSE
  summary: wrapper for clock_gettime version compatibility
  description: |
    This is a wrapper package to map clock_gettime_GLIBC_PRIVATE to GLIBC_2.17
  doc_url: 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
